services:
  frontend:
    image: nikprime/nikantipin.front:master
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - common.env
    networks:
      - default

  backend:
    restart: always
    image: nikprime/nikantipin.back:master
    ports:
      - "3000:3000"
    env_file:
      - ./common.env
    networks:
      - default