services:
  frontend:
    image: nikprime/nikantipin.front
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - common.env
    secrets:
      - BASE_API_URL

  backend:
    image: nikprime/nikantipin.back
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - common.env

  postgres:
    image: postgres:15.1
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - common.env
    ports:
      - "5432:5432"