services:
  postgres:
    image: postgres:15.1
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - common.env
    ports:
      - "5432:5432"

  frontend:
    image: nikprime/nikantipin.front:master
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - common.env

  backend:
    restart: always
    image: nikprime/nikantipin.back:master
    depends_on:
    - postgres
    ports:
      - "3000:3000"
    env_file:
      - ./common.env